# Generated by Django 3.1.2 on 2021-09-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_sales_items_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfg',
        ),
    ]
