# Generated by Django 3.1.2 on 2021-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210925_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=True, max_length=1000),
            preserve_default=False,
        ),
    ]
