# Generated by Django 3.1.2 on 2021-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='items_json',
            field=models.CharField(default=True, max_length=900),
            preserve_default=False,
        ),
    ]
